---
title: "Module SPA2 : Distance et accessibilité"
subtitle: "CIST EE2023, Ouidah, Bénin"
author: "Varamoko Bamba & Claude Grasland"
---

Ce site est la version **provisoire** du cours d'analyse spatiale sur la distance et l'accessibilité qui sera dispensé lors de l'école d'été CIST 2023 à Ouidah au Bénin. Il a été mis au point par Claude Grasland (Géographe, Université Paris Cité) et Vakaramoko Bamba (Géographe, Université d'Abidjan) puis relu et complété par les autres formateurs. 

Le **cours** présente le concept général de distance à l'aide d'exemples concrets puis décrit différentes mesures d'accessibilité que l'on peut déduire d'unematrice de distance

Les **exercices d'applications sous R** permettent d'appliquer le cours sur des exemples concrets.

- L'**application n°1** utilise un tableau de **données d'enquête** permettant de décrire les marchandises qui entrent et sortes du marché de Bouaké. Les exercices portent sur l'analyse comparée de la circulation des différents produits qui entrent ou sortent du marché de Bouaké (maïs, oignons, ignames, riz,etc)
- L'**application n°2** utilise des fonds de carte du premier niveau de division régionale de plusieurs pays (Bénin, Burkina Faso, Côte d'Ivoire, Mali, Niger, Sénégal, Togo, ...). A partir des coordonnées des chef-lieux de ces régions, on construit différents **matrices de distances** afin d'en déduire les régions les plus accessibles (en temps, en kilomètres) et les régions ayant les réseaux routiers les plus efficaces (faible sinuosité, vitesse importante)

N'hésitez pas à faire part de vos remarques ou critiques aux auteurs :

Claude Grasland : <claude.grasland@parisgeo.cnrs.fr>
Varamoko Bamba : <bvakaramoko81@gmail.com>